name: CI - Test and Build

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Enable pnpm
      run: corepack enable pnpm

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run linting
      run: pnpm lint

    - name: Run type checking
      run: pnpm run type-check

    - name: Build application
      run: pnpm build
      env:
        # Use dummy values for build testing
        NEXT_PUBLIC_FIREBASE_API_KEY: "dummy-api-key"
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "dummy.firebaseapp.com"
        NEXT_PUBLIC_FIREBASE_DATABASE_URL: "https://dummy-default-rtdb.firebaseio.com/"
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: "dummy-project"
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "dummy.appspot.com"
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "123456789"
        NEXT_PUBLIC_FIREBASE_APP_ID: "1:123456789:web:dummy"
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: "dummy-client-id.apps.googleusercontent.com"

    - name: Test Docker build
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY="dummy-api-key" \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="dummy.firebaseapp.com" \
          --build-arg NEXT_PUBLIC_FIREBASE_DATABASE_URL="https://dummy-default-rtdb.firebaseio.com/" \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID="dummy-project" \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="dummy.appspot.com" \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="123456789" \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID="1:123456789:web:dummy" \
          --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID="dummy-client-id.apps.googleusercontent.com" \
          -t sync-gsheet:test .

    - name: Test results
      run: |
        echo "✅ All tests passed!"
        echo "✅ Linting successful!"
        echo "✅ Type checking successful!"
        echo "✅ Build successful!"
        echo "✅ Docker build successful!"
